<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Supplier extends Model
{
    use HasFactory;

    protected $table = 'supplier';
    protected $fillable = [
        'id_supplier', 'nama', 'alamat', 'no_telepon', 'no_hp','id_tipe_supplier','npwp','id_akun_hutang','id_akun_piutang','nama_pic'
    ];

    public function pesanan()
    {
        return $this->hasOne(PembelianPesanan::class, 'supplier_id', 'id');
    }

    public function penerimaan()
    {
        return $this->belongsTo(PembelianPenerimaan::class, 'id');
    }

    public function kategoriSuppliers()
    {
        return $this->hasMany(TipeKontak::class, 'id','id_tipe_supplier');
    }

    public function toArray()
    {
        $toArray = parent::toArray(); // TODO: Change the autogenerated stub
        $toArray['picture_path'] = $this->PicturePath;
        return $toArray;
    }
    public function getPicturePathAttribute()
    {
        $image = Storage::disk('public')->files('supplier/'.$this->id);

        if (!empty($image[0]))
            return url('').'/storage/' . $image[0];

    }

}
