<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, HasRoles, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = ["name", "email", "password",'cabang_unit', 'profil_id','telepon','sub_branch_unit', 'anggota_id', 'ao_id', ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = ["password", "remember_token"];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        "email_verified_at" => "datetime",
    ];
    public function toArray()
    {
        $toArray = parent::toArray(); // TODO: Change the autogenerated stub
        $toArray['profil'] = $this->PicturePathprofil;
        return $toArray;
    }
    public function getPicturePathprofilAttribute()
    {
        $image = Storage::disk('public')->files('profil/'.$this->id);

        if (!empty($image[0]))
            return url('').'/storage/' . $image[0];

    }
}
