<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Zpengajuan extends Model
{
    use HasFactory;

    protected $table = 'zpengajuans';
    protected $guarded = ['id'];

    public function toArray()
    {
        $toArray = parent::toArray(); // TODO: Change the autogenerated stub
        $toArray['ktp_pengajuan'] = $this->PicturePath;
        $toArray['selfi_pengajuan'] = $this->PicturePathselfi;
        $toArray['wartung0_pengajuan'] = $this->PicturePathwarung0;
        $toArray['wartung1_pengajuan'] = $this->PicturePathwarung1;
        return $toArray;
    }
    public function getPicturePathAttribute()
    {
        $image = Storage::disk('public')->files('ktp_pengajuan/'.$this->id);

        if (!empty($image[0]))
            return url('').'/storage/' . $image[0];

    }
    public function getPicturePathselfiAttribute()
    {
        $image = Storage::disk('public')->files('selfi_pengajuan/'.$this->id);

        if (!empty($image[0]))
            return url('').'/storage/' . $image[0];

    }
    public function getPicturePathwarung0Attribute()
    {
        $image = Storage::disk('public')->files('warung0_pengajuan/'.$this->id);

        if (!empty($image[0]))
            return url('').'/storage/' . $image[0];

    }
    public function getPicturePathwarung1Attribute()
    {
        $image = Storage::disk('public')->files('warung1_pengajuan/'.$this->id);

        if (!empty($image[0]))
            return url('').'/storage/' . $image[0];

    }

}
